### ISSUE TITLE
Be able to create A new annotated feature from an uploaded video

### ISSUE THREAD

**Issue by jsmentch** [jsmentch/feature_visualizer#13]

**Comment by darius522** [comment]
Added the initial implementation to my branch. "new_feature" should be selected from the feature table in order to create a new feature, it will then be treated as any other feature that could be edited and downloaded (edit mode is automatically toggled-on on feature creation). Here are a couple of enhancements I can think of, for now:

- Allow for user-defined file name ON feature creation (as opposed to solely when being downloaded). Right now the newly created feature holds the name "new_feature", which isn't meaningful and doesn't allow for multiple user-created features to co-exist within the same "session".
- Allow user-defined lower and upper bounds and switch to non-binary feature values
